development:
  adapter: mysql2
  database: sphinx
  username: root
  encoding: utf8
  host: localhost
  

test:
  adapter: mysql2
  database: sphinx
  username: root
  encoding: utf8
  host: localhost
  
production:
  adapter: mysql2
  database: sphinx
  username: root
  encoding: utf8
  host: localhost
  